[package]
name = "benchmarking"
version = "0.2.0"
authors = ["Magic Len <len@magiclen.org>"]
homepage = "https://magiclen.org/benchmarking"
keywords = ["benchmark", "bench", "execution", "time"]
description= "This crate can be used to execute something and measure the execution time in nano seconds. It does not output anything to the screen and the filesystem."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/benchmarking", branch = "master" }
appveyor = { repository = "magiclen/benchmarking", branch = "master", service = "github" }

[dependencies]